# Generated by Django 6.1 on 2026-08-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('tagline', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('services', models.TextField(help_text='Enter one service per line.')),
                ('who_its_for', models.TextField(verbose_name="Who it's for")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['number'],
            },
        ),
    ]
